/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPrettierArchitectureRouteImport } from './routes/posts/prettier-architecture'
import { Route as PostsJsxAsStateRouteImport } from './routes/posts/jsx-as-state'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPrettierArchitectureRoute =
  PostsPrettierArchitectureRouteImport.update({
    id: '/posts/prettier-architecture',
    path: '/posts/prettier-architecture',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsJsxAsStateRoute = PostsJsxAsStateRouteImport.update({
  id: '/posts/jsx-as-state',
  path: '/posts/jsx-as-state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/posts/jsx-as-state': typeof PostsJsxAsStateRoute
  '/posts/prettier-architecture': typeof PostsPrettierArchitectureRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/posts/jsx-as-state': typeof PostsJsxAsStateRoute
  '/posts/prettier-architecture': typeof PostsPrettierArchitectureRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/posts/jsx-as-state': typeof PostsJsxAsStateRoute
  '/posts/prettier-architecture': typeof PostsPrettierArchitectureRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/posts/jsx-as-state'
    | '/posts/prettier-architecture'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/posts/jsx-as-state'
    | '/posts/prettier-architecture'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/resume'
    | '/posts/jsx-as-state'
    | '/posts/prettier-architecture'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeRoute: typeof ResumeRoute
  PostsJsxAsStateRoute: typeof PostsJsxAsStateRoute
  PostsPrettierArchitectureRoute: typeof PostsPrettierArchitectureRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/prettier-architecture': {
      id: '/posts/prettier-architecture'
      path: '/posts/prettier-architecture'
      fullPath: '/posts/prettier-architecture'
      preLoaderRoute: typeof PostsPrettierArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/jsx-as-state': {
      id: '/posts/jsx-as-state'
      path: '/posts/jsx-as-state'
      fullPath: '/posts/jsx-as-state'
      preLoaderRoute: typeof PostsJsxAsStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeRoute: ResumeRoute,
  PostsJsxAsStateRoute: PostsJsxAsStateRoute,
  PostsPrettierArchitectureRoute: PostsPrettierArchitectureRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
